function MindlinPlateAnalysisHub
% MindlinPlateAnalysisHub - GUI control hub for Mindlin plate analysis
% This program creates a graphical interface to analyze Mindlin plates
% with different boundary conditions, material properties, and mesh sizes.
% Each analysis type opens in a separate window for better comparison.

% Create main control figure
figControl = figure('Name', 'Mindlin Plate Analysis Hub', ...
    'NumberTitle', 'off', ...
    'Position', [100, 100, 800, 700], ...
    'MenuBar', 'none', ...
    'ToolBar', 'none', ...
    'Color', [0.94 0.94 0.94]);

% Analysis Type Panel
panelAnalysis = uipanel(figControl, 'Title', 'Analysis Type', ...
    'Position', [0.05, 0.9, 0.9, 0.08], ...
    'BackgroundColor', [0.94 0.94 0.94]);

uicontrol(panelAnalysis, 'Style', 'text', ...
    'String', 'Select Analysis:', ...
    'Position', [20, 20, 100, 20], ...
    'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.94 0.94 0.94]);
popupAnalysis = uicontrol(panelAnalysis, 'Style', 'popupmenu', ...
    'String', {'Static Analysis', 'Buckling Analysis', 'Free Vibration'}, ...
    'Position', [130, 20, 200, 25], ...
    'Value', 1, ...
    'Callback', @analysisTypeChanged);

% Material Properties Panel
panelMaterial = uipanel(figControl, 'Title', 'Material Properties', ...
    'Position', [0.05, 0.72, 0.9, 0.16], ...
    'BackgroundColor', [0.94 0.94 0.94]);

% Young's modulus
uicontrol(panelMaterial, 'Style', 'text', ...
    'String', 'Young''s Modulus (E):', ...
    'Position', [20, 70, 150, 20], ...
    'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.94 0.94 0.94]);
editE = uicontrol(panelMaterial, 'Style', 'edit', ...
    'String', '210e9', ...
    'Position', [180, 70, 100, 25], ...
    'BackgroundColor', 'white');
uicontrol(panelMaterial, 'Style', 'text', ...
    'String', 'Pa', ...
    'Position', [285, 70, 30, 20], ...
    'BackgroundColor', [0.94 0.94 0.94]);

% Poisson's ratio
uicontrol(panelMaterial, 'Style', 'text', ...
    'String', 'Poisson''s Ratio:', ...
    'Position', [20, 35, 150, 20], ...
    'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.94 0.94 0.94]);
editPoisson = uicontrol(panelMaterial, 'Style', 'edit', ...
    'String', '0.3', ...
    'Position', [180, 35, 100, 25], ...
    'BackgroundColor', 'white');

% Material density
uicontrol(panelMaterial, 'Style', 'text', ...
    'String', 'Density:', ...
    'Position', [350, 70, 100, 20], ...
    'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.94 0.94 0.94]);
editDensity = uicontrol(panelMaterial, 'Style', 'edit', ...
    'String', '7850', ...
    'Position', [450, 70, 100, 25], ...
    'Enable', 'off', ...
    'BackgroundColor', 'white');
uicontrol(panelMaterial, 'Style', 'text', ...
    'String', 'kg/m³', ...
    'Position', [555, 70, 40, 20], ...
    'BackgroundColor', [0.94 0.94 0.94]);

% Shear correction factor
uicontrol(panelMaterial, 'Style', 'text', ...
    'String', 'Shear Correction:', ...
    'Position', [350, 35, 100, 20], ...
    'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.94 0.94 0.94]);
editKapa = uicontrol(panelMaterial, 'Style', 'edit', ...
    'String', '5/6', ...
    'Position', [450, 35, 100, 25], ...
    'BackgroundColor', 'white');

% Geometry Panel
panelGeometry = uipanel(figControl, 'Title', 'Plate Geometry', ...
    'Position', [0.05, 0.54, 0.9, 0.16], ...
    'BackgroundColor', [0.94 0.94 0.94]);

% Length
uicontrol(panelGeometry, 'Style', 'text', ...
    'String', 'Length (L):', ...
    'Position', [20, 70, 150, 20], ...
    'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.94 0.94 0.94]);
editLength = uicontrol(panelGeometry, 'Style', 'edit', ...
    'String', '1.0', ...
    'Position', [180, 70, 100, 25], ...
    'BackgroundColor', 'white');
uicontrol(panelGeometry, 'Style', 'text', ...
    'String', 'm', ...
    'Position', [285, 70, 20, 20], ...
    'BackgroundColor', [0.94 0.94 0.94]);

% Width
uicontrol(panelGeometry, 'Style', 'text', ...
    'String', 'Width (W):', ...
    'Position', [350, 70, 100, 20], ...
    'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.94 0.94 0.94]);
editWidth = uicontrol(panelGeometry, 'Style', 'edit', ...
    'String', '1.0', ...
    'Position', [450, 70, 100, 25], ...
    'BackgroundColor', 'white');
uicontrol(panelGeometry, 'Style', 'text', ...
    'String', 'm', ...
    'Position', [555, 70, 20, 20], ...
    'BackgroundColor', [0.94 0.94 0.94]);

% Thickness
uicontrol(panelGeometry, 'Style', 'text', ...
    'String', 'Thickness (h):', ...
    'Position', [20, 35, 150, 20], ...
    'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.94 0.94 0.94]);
editThickness = uicontrol(panelGeometry, 'Style', 'edit', ...
    'String', '0.01', ...
    'Position', [180, 35, 100, 25], ...
    'BackgroundColor', 'white');
uicontrol(panelGeometry, 'Style', 'text', ...
    'String', 'm', ...
    'Position', [285, 35, 20, 20], ...
    'BackgroundColor', [0.94 0.94 0.94]);

% Mesh Panel
panelMesh = uipanel(figControl, 'Title', 'Mesh Properties', ...
    'Position', [0.05, 0.42, 0.9, 0.1], ...
    'BackgroundColor', [0.94 0.94 0.94]);

% Elements in X
uicontrol(panelMesh, 'Style', 'text', ...
    'String', 'Elements in X:', ...
    'Position', [20, 20, 150, 20], ...
    'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.94 0.94 0.94]);
editElementsX = uicontrol(panelMesh, 'Style', 'edit', ...
    'String', '20', ...
    'Position', [180, 20, 100, 25], ...
    'BackgroundColor', 'white');

% Elements in Y
uicontrol(panelMesh, 'Style', 'text', ...
    'String', 'Elements in Y:', ...
    'Position', [350, 20, 150, 20], ...
    'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.94 0.94 0.94]);
editElementsY = uicontrol(panelMesh, 'Style', 'edit', ...
    'String', '20', ...
    'Position', [450, 20, 100, 25], ...
    'BackgroundColor', 'white');

% Load and Boundary Panel
panelBC = uipanel(figControl, 'Title', 'Load and Boundary Conditions', ...
    'Position', [0.05, 0.22, 0.9, 0.18], ...
    'BackgroundColor', [0.94 0.94 0.94]);

% Load value
uicontrol(panelBC, 'Style', 'text', ...
    'String', 'Load Value:', ...
    'Position', [20, 80, 150, 20], ...
    'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.94 0.94 0.94]);
editLoad = uicontrol(panelBC, 'Style', 'edit', ...
    'String', '-1000', ...
    'Position', [180, 80, 100, 25], ...
    'BackgroundColor', 'white');
uicontrol(panelBC, 'Style', 'text', ...
    'String', 'N/m²', ...
    'Position', [285, 80, 40, 20], ...
    'BackgroundColor', [0.94 0.94 0.94]);

% Load type for buckling
uicontrol(panelBC, 'Style', 'text', ...
    'String', 'Load Type:', ...
    'Position', [350, 80, 100, 20], ...
    'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.94 0.94 0.94]);
popupLoadType = uicontrol(panelBC, 'Style', 'popupmenu', ...
    'String', {'Uniform Pressure', 'Uniaxial Compression', 'Biaxial Compression'}, ...
    'Position', [450, 80, 150, 25], ...
    'Enable', 'off');

% Edge boundary conditions
uicontrol(panelBC, 'Style', 'text', ...
    'String', 'Edge Conditions:', ...
    'Position', [20, 40, 150, 20], ...
    'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.94 0.94 0.94]);

% Individual edge conditions
sides = {'Left', 'Right', 'Top', 'Bottom'};
edgeTypes = {'Free (F)', 'Simply Supported (S)', 'Clamped (C)'};
popupEdges = zeros(4,1);
for i = 1:4
    uicontrol(panelBC, 'Style', 'text', ...
        'String', [sides{i} ':'], ...
        'Position', [180+150*(i-1), 40, 40, 20], ...
        'BackgroundColor', [0.94 0.94 0.94]);
    popupEdges(i) = uicontrol(panelBC, 'Style', 'popupmenu', ...
        'String', edgeTypes, ...
        'Position', [220+150*(i-1), 40, 100, 25], ...
        'Value', 2);  % Default to Simply Supported
end

% Results Panel
panelResults = uipanel(figControl, 'Title', 'Results Display', ...
    'Position', [0.05, 0.11, 0.9, 0.09], ...
    'BackgroundColor', [0.94 0.94 0.94]);

% Plot selection
uicontrol(panelResults, 'Style', 'text', ...
    'String', 'Plot Type:', ...
    'Position', [20, 20, 100, 20], ...
    'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.94 0.94 0.94]);
popupPlotType = uicontrol(panelResults, 'Style', 'popupmenu', ...
    'String', {'All Results', 'Mesh Only', 'Deformation', 'Contour Plot'}, ...
    'Position', [130, 20, 150, 25]);

% Control Panel
panelControl = uipanel(figControl, 'Title', 'Analysis Control', ...
    'Position', [0.05, 0.02, 0.9, 0.07], ...
    'BackgroundColor', [0.94 0.94 0.94]);

% Run button
uicontrol(panelControl, 'Style', 'pushbutton', ...
    'String', 'Run Analysis', ...
    'Position', [300, 10, 200, 30], ...
    'FontWeight', 'bold', ...
    'BackgroundColor', [0.47 0.67 0.19], ...
    'ForegroundColor', 'white', ...
    'Callback', @runAnalysis);

    function analysisTypeChanged(~, ~)
        % Enable/disable relevant controls based on analysis type
        analysisType = get(popupAnalysis, 'Value');
        
        if analysisType == 3  % Vibration analysis
            set(editDensity, 'Enable', 'on');
            set(popupLoadType, 'Enable', 'off');
            set(editLoad, 'Enable', 'off');
        elseif analysisType == 2  % Buckling analysis
            set(editDensity, 'Enable', 'off');
            set(popupLoadType, 'Enable', 'on');
            set(editLoad, 'Enable', 'on');
        else  % Static analysis
            set(editDensity, 'Enable', 'off');
            set(popupLoadType, 'Enable', 'off');
            set(editLoad, 'Enable', 'on');
        end
    end

    function runAnalysis(~, ~)
        % Get analysis parameters
        params = struct();
        params.analysisType = get(popupAnalysis, 'Value');
        params.E = str2double(get(editE, 'String'));
        params.poisson = str2double(get(editPoisson, 'String'));
        params.thickness = str2double(get(editThickness, 'String'));
        params.L = str2double(get(editLength, 'String'));
        params.W = str2double(get(editWidth, 'String'));
        params.nx = str2double(get(editElementsX, 'String'));
        params.ny = str2double(get(editElementsY, 'String'));
        params.loadValue = str2double(get(editLoad, 'String'));
        params.plotType = get(popupPlotType, 'Value');
        
        % Handle shear correction factor
        kapaStr = get(editKapa, 'String');
        if contains(kapaStr, '/')
            parts = strsplit(kapaStr, '/');
            params.kapa = str2double(parts{1}) / str2double(parts{2});
        else
            params.kapa = str2double(kapaStr);
        end
        
        % Get boundary conditions
        bcString = '';
        for i = 1:4
            val = get(popupEdges(i), 'Value');
            switch val
                case 1
                    bcString(i) = 'F';
                case 2
                    bcString(i) = 'S';
                case 3
                    bcString(i) = 'C';
            end
        end
        params.boundaryConditions = bcString;
        
        % Add analysis-specific parameters
        if params.analysisType == 3  % Vibration
            params.density = str2double(get(editDensity, 'String'));
        elseif params.analysisType == 2  % Buckling
            params.loadType = get(popupLoadType, 'Value');
        end
        
        % Create new figure window for results
        switch params.analysisType
            case 1
                showStaticResults(params);
            case 2
                showBucklingResults(params);
            case 3
                showVibrationResults(params);
        end
    end
end

function showStaticResults(params)
    % Create new figure window for static analysis results
    figResults = figure('Name', 'Static Analysis Results', ...
        'NumberTitle', 'off', ...
        'Position', [850, 100, 900, 600]);
    
    % Run analysis
    [nodes, elements] = generateMesh(params.L, params.W, params.nx, params.ny);
    [K, F] = assembleSystem(nodes, elements, params.E, params.poisson, ...
        params.thickness, params.loadValue);
    [K_mod, F_mod] = applyBoundaryConditions(K, F, nodes, params.boundaryConditions);
    U = K_mod\F_mod;
    
    % Plot based on selected plot type
    if params.plotType == 1 || params.plotType == 2  % All or Mesh
        subplot(2,2,1);
        drawingMesh(nodes, elements, 'Q4', 'k-');
        title('Original Mesh');
        axis equal tight;
    end
    
    if params.plotType == 1 || params.plotType == 3  % All or Deformation
        subplot(2,2,2);
        plotDeformedShape(nodes, elements, U);
        title('Deformed Shape');
    end
    
    if params.plotType == 1 || params.plotType == 4  % All or Contour
        subplot(2,2,3);
        plotContour(nodes, elements, U);
        title('Displacement Contour');
    end
    
    if params.plotType == 1  % Show results table for "All" option
        subplot(2,2,4);
        showResults(params, U);
    end
end

function showBucklingResults(params)
    % Create new figure window for buckling analysis results
    figResults = figure('Name', 'Buckling Analysis Results', ...
        'NumberTitle', 'off', ...
        'Position', [850, 100, 900, 600]);
    
    % Run buckling analysis
    [nodes, elements] = generateMesh(params.L, params.W, params.nx, params.ny);
    [K, ~] = assembleSystem(nodes, elements, params.E, params.poisson, ...
        params.thickness, 0);
    Kg = assembleGeometricStiffness(nodes, elements, params.loadValue);
    [K_mod, Kg_mod] = applyBucklingBoundaryConditions(K, Kg, nodes, params.boundaryConditions);
    [V, D] = eigs(K_mod, Kg_mod, 5, 'smallestabs');
    
    % Plot results
    if params.plotType == 1 || params.plotType == 2
        subplot(2,2,1);
        drawingMesh(nodes, elements, 'Q4', 'k-');
        title('Original Mesh');
        axis equal tight;
    end
    
    if params.plotType == 1 || params.plotType == 3
        subplot(2,2,2);
        plotDeformedShape(nodes, elements, V(:,1));
        title('First Buckling Mode');
    end
    
    if params.plotType == 1 || params.plotType == 4
        subplot(2,2,3);
        plotContour(nodes, elements, V(:,1));
        title('Buckling Mode Contour');
    end
    
    if params.plotType == 1
        subplot(2,2,4);
        showBucklingResults(params, D);
    end
end

function showVibrationResults(params)
    % Create new figure window for vibration analysis results
    figResults = figure('Name', 'Vibration Analysis Results', ...
        'NumberTitle', 'off', ...
        'Position', [850, 100, 900, 600]);
    
    % Run vibration analysis
    [nodes, elements] = generateMesh(params.L, params.W, params.nx, params.ny);
    [K, ~] = assembleSystem(nodes, elements, params.E, params.poisson, ...
        params.thickness, 0);
    M = assembleMassMatrix(nodes, elements, params.density, params.thickness);
    [K_mod, M_mod] = applyVibrationBoundaryConditions(K, M, nodes, params.boundaryConditions);
    [V, D] = eigs(K_mod, M_mod, 5, 'smallestabs');
    frequencies = sqrt(diag(D))/(2*pi);
    
    % Plot results
    if params.plotType == 1 || params.plotType == 2
        subplot(2,2,1);
        drawingMesh(nodes, elements, 'Q4', 'k-');
        title('Original Mesh');
        axis equal tight;
    end
    
    if params.plotType == 1 || params.plotType == 3
        subplot(2,2,2);
        plotDeformedShape(nodes, elements, V(:,1));
        title('First Mode Shape');
    end
    
    if params.plotType == 1 || params.plotType == 4
        subplot(2,2,3);
        plotContour(nodes, elements, V(:,1));
        title('Mode Shape Contour');
    end
    
    if params.plotType == 1
        subplot(2,2,4);
        showVibrationResults(params, frequencies);
    end
end

function plotDeformedShape(nodes, elements, U)
    plot3(nodes(:,1), nodes(:,2), U(1:size(nodes,1)), '.');
    xlabel('X'); ylabel('Y'); zlabel('Displacement');
    axis tight; grid on;
end

function plotContour(nodes, elements, U)
    x = nodes(:,1);
    y = nodes(:,2);
    z = U(1:size(nodes,1));
    tri = delaunay(x, y);
    trisurf(tri, x, y, z);
    view(2); shading interp;
    colorbar; axis equal tight;
end

function showResults(params, U)
    axis off;
    centerDisp = min(U);
    D = params.E*params.thickness^3/(12*(1-params.poisson^2));
    normalizedDisp = centerDisp*D/params.L^4;
    
    text(0.1, 0.9, ['BC: ' params.boundaryConditions], 'FontWeight', 'bold');
    text(0.1, 0.8, ['E = ' num2str(params.E,'%.2e') ' Pa']);
    text(0.1, 0.7, [num2str(params.L) 'm × ' num2str(params.W) 'm × ' num2str(params.thickness) 'm']);
    text(0.1, 0.6, ['Load: ' num2str(params.loadValue) ' N/m²']);
    text(0.1, 0.5, ['Max disp: ' num2str(centerDisp,'%.2e') ' m']);
    text(0.1, 0.4, ['Normalized: ' num2str(normalizedDisp,'%.6f')]);
end

function showBucklingResults(params, D)
    axis off;
    lambdas = sort(diag(D));
    text(0.1, 0.9, 'Critical Load Factors:', 'FontWeight', 'bold');
    for i = 1:min(5,length(lambdas))
        text(0.1, 0.9-i*0.1, sprintf('λ%d = %.4f', i, lambdas(i)));
    end
end

function showVibrationResults(params, frequencies)
    axis off;
    text(0.1, 0.9, 'Natural Frequencies:', 'FontWeight', 'bold');
    for i = 1:min(5,length(frequencies))
        text(0.1, 0.9-i*0.1, sprintf('f%d = %.2f Hz', i, frequencies(i)));
    end
end