function MindlinPlateAnalysisHub
% MindlinPlateAnalysisHub - Enhanced GUI control hub for Mindlin plate analysis
% This program creates a modern graphical interface to analyze Mindlin plates
% with different boundary conditions, material properties, and mesh sizes.

% Create main control figure with modern styling
backgroundColor = [0.97 0.97 0.97];
panelColor = [0.94 0.94 0.94];
accentColor = [0.3 0.6 0.9];
buttonColor = [0.47 0.67 0.19];

% Set figure window properties
figControl = figure('Name', 'Mindlin Plate Analysis Hub', ...
    'NumberTitle', 'off', ...
    'Position', [100, 100, 800, 750], ...
    'MenuBar', 'none', ...
    'ToolBar', 'none', ...
    'Color', backgroundColor, ...
    'Units', 'pixels', ...
    'Resize', 'off');

% Add menu bar
menubar = uimenu(figControl, 'Label', 'File');
uimenu(menubar, 'Label', 'New Analysis', 'Callback', @newAnalysis);
uimenu(menubar, 'Label', 'Load Configuration...', 'Callback', @loadConfig);
uimenu(menubar, 'Label', 'Save Configuration...', 'Callback', @saveConfig);
uimenu(menubar, 'Label', 'Export Results...', 'Callback', @exportResults, 'Enable', 'off');
uimenu(menubar, 'Label', 'Exit', 'Separator', 'on', 'Callback', 'close(gcf)');

% Add comparison menu
compareMenu = uimenu(figControl, 'Label', 'Compare');
uimenu(compareMenu, 'Label', 'Load Previous Results...', 'Callback', @loadPreviousResults);
uimenu(compareMenu, 'Label', 'Compare Analyses', 'Callback', @compareAnalyses, 'Enable', 'off');

% Add help menu
helpMenu = uimenu(figControl, 'Label', 'Help');
uimenu(helpMenu, 'Label', 'Documentation', 'Callback', @showDocumentation);
uimenu(helpMenu, 'Label', 'About', 'Callback', @showAbout);

% Add help button in top right
helpBtn = uicontrol(figControl, 'Style', 'pushbutton', ...
    'String', '?', ...
    'Position', [760, 710, 30, 30], ...
    'FontWeight', 'bold', ...
    'BackgroundColor', accentColor, ...
    'ForegroundColor', 'white', ...
    'Callback', @showHelp, ...
    'TooltipString', 'Click for help and usage instructions');

% Analysis Type Panel with enhanced styling
panelAnalysis = uipanel(figControl, 'Title', 'Analysis Type', ...
    'Position', [0.05, 0.9, 0.9, 0.08], ...
    'BackgroundColor', panelColor, ...
    'ForegroundColor', accentColor, ...
    'FontWeight', 'bold', ...
    'HighlightColor', accentColor);

uicontrol(panelAnalysis, 'Style', 'text', ...
    'String', 'Select Analysis:', ...
    'Position', [20, 20, 100, 20], ...
    'HorizontalAlignment', 'left', ...
    'BackgroundColor', panelColor);

popupAnalysis = uicontrol(panelAnalysis, 'Style', 'popupmenu', ...
    'String', {'Static Analysis', 'Buckling Analysis', 'Free Vibration'}, ...
    'Position', [130, 20, 200, 25], ...
    'Value', 1, ...
    'Callback', @updateAnalysisType);

% Material Properties Panel with enhanced validation
panelMaterial = uipanel(figControl, 'Title', 'Material Properties', ...
    'Position', [0.05, 0.72, 0.9, 0.16], ...
    'BackgroundColor', panelColor, ...
    'ForegroundColor', accentColor, ...
    'FontWeight', 'bold', ...
    'HighlightColor', accentColor);

uicontrol(panelMaterial, 'Style', 'text', ...
    'String', 'Young''s Modulus (E):', ...
    'Position', [20, 70, 150, 20], ...
    'HorizontalAlignment', 'left', ...
    'BackgroundColor', panelColor);
editE = uicontrol(panelMaterial, 'Style', 'edit', ...
    'String', '210e9', ...
    'Position', [180, 70, 100, 25], ...
    'BackgroundColor', 'white', ...
    'Callback', @validateNumericInput);
uicontrol(panelMaterial, 'Style', 'text', ...
    'String', 'Pa', ...
    'Position', [285, 70, 30, 20], ...
    'BackgroundColor', panelColor);

uicontrol(panelMaterial, 'Style', 'text', ...
    'String', 'Poisson''s Ratio:', ...
    'Position', [20, 35, 150, 20], ...
    'HorizontalAlignment', 'left', ...
    'BackgroundColor', panelColor);
editPoisson = uicontrol(panelMaterial, 'Style', 'edit', ...
    'String', '0.3', ...
    'Position', [180, 35, 100, 25], ...
    'BackgroundColor', 'white', ...
    'Callback', @validateNumericInput);

uicontrol(panelMaterial, 'Style', 'text', ...
    'String', 'Density:', ...
    'Position', [350, 70, 100, 20], ...
    'HorizontalAlignment', 'left', ...
    'BackgroundColor', panelColor);
editDensity = uicontrol(panelMaterial, 'Style', 'edit', ...
    'String', '7850', ...
    'Position', [450, 70, 100, 25], ...
    'Enable', 'off', ...
    'BackgroundColor', 'white', ...
    'Callback', @validateNumericInput);
uicontrol(panelMaterial, 'Style', 'text', ...
    'String', 'kg/m³', ...
    'Position', [555, 70, 40, 20], ...
    'BackgroundColor', panelColor);

uicontrol(panelMaterial, 'Style', 'text', ...
    'String', 'Shear Correction:', ...
    'Position', [350, 35, 100, 20], ...
    'HorizontalAlignment', 'left', ...
    'BackgroundColor', panelColor);
editKapa = uicontrol(panelMaterial, 'Style', 'edit', ...
    'String', '5/6', ...
    'Position', [450, 35, 100, 25], ...
    'BackgroundColor', 'white', ...
    'Callback', @validateFractionInput);

% Geometry Panel with enhanced styling
panelGeometry = uipanel(figControl, 'Title', 'Plate Geometry', ...
    'Position', [0.05, 0.54, 0.9, 0.16], ...
    'BackgroundColor', panelColor, ...
    'ForegroundColor', accentColor, ...
    'FontWeight', 'bold', ...
    'HighlightColor', accentColor);

% Add dimension inputs
uicontrol(panelGeometry, 'Style', 'text', ...
    'String', 'Length (L):', ...
    'Position', [20, 70, 100, 20], ...
    'HorizontalAlignment', 'left', ...
    'BackgroundColor', panelColor);

editLength = uicontrol(panelGeometry, 'Style', 'edit', ...
    'String', '1.0', ...
    'Position', [120, 70, 100, 25], ...
    'BackgroundColor', 'white', ...
    'Callback', @validateNumericInput);

uicontrol(panelGeometry, 'Style', 'text', ...
    'String', 'm', ...
    'Position', [225, 70, 20, 20], ...
    'BackgroundColor', panelColor);

uicontrol(panelGeometry, 'Style', 'text', ...
    'String', 'Width (W):', ...
    'Position', [280, 70, 100, 20], ...
    'HorizontalAlignment', 'left', ...
    'BackgroundColor', panelColor);

editWidth = uicontrol(panelGeometry, 'Style', 'edit', ...
    'String', '1.0', ...
    'Position', [380, 70, 100, 25], ...
    'BackgroundColor', 'white', ...
    'Callback', @validateNumericInput);

uicontrol(panelGeometry, 'Style', 'text', ...
    'String', 'm', ...
    'Position', [485, 70, 20, 20], ...
    'BackgroundColor', panelColor);

uicontrol(panelGeometry, 'Style', 'text', ...
    'String', 'Thickness (h):', ...
    'Position', [20, 35, 100, 20], ...
    'HorizontalAlignment', 'left', ...
    'BackgroundColor', panelColor);

editThickness = uicontrol(panelGeometry, 'Style', 'edit', ...
    'String', '0.01', ...
    'Position', [120, 35, 100, 25], ...
    'BackgroundColor', 'white', ...
    'Callback', @validateNumericInput);

uicontrol(panelGeometry, 'Style', 'text', ...
    'String', 'm', ...
    'Position', [225, 35, 20, 20], ...
    'BackgroundColor', panelColor);

% Mesh Panel with visual preview
panelMesh = uipanel(figControl, 'Title', 'Mesh Properties', ...
    'Position', [0.05, 0.42, 0.9, 0.1], ...
    'BackgroundColor', panelColor, ...
    'ForegroundColor', accentColor, ...
    'FontWeight', 'bold', ...
    'HighlightColor', accentColor);

% Add mesh density controls
uicontrol(panelMesh, 'Style', 'text', ...
    'String', 'Elements X:', ...
    'Position', [20, 20, 100, 20], ...
    'HorizontalAlignment', 'left', ...
    'BackgroundColor', panelColor);

editElementsX = uicontrol(panelMesh, 'Style', 'edit', ...
    'String', '10', ...
    'Position', [120, 20, 60, 25], ...
    'BackgroundColor', 'white', ...
    'Callback', @validateIntegerInput);

uicontrol(panelMesh, 'Style', 'text', ...
    'String', 'Elements Y:', ...
    'Position', [200, 20, 100, 20], ...
    'HorizontalAlignment', 'left', ...
    'BackgroundColor', panelColor);

editElementsY = uicontrol(panelMesh, 'Style', 'edit', ...
    'String', '10', ...
    'Position', [300, 20, 60, 25], ...
    'BackgroundColor', 'white', ...
    'Callback', @validateIntegerInput);

% Add mesh preview button
uicontrol(panelMesh, 'Style', 'pushbutton', ...
    'String', 'Preview Mesh', ...
    'Position', [580, 20, 100, 25], ...
    'Callback', @previewMesh, ...
    'TooltipString', 'Show mesh preview');

% Add thermal load panel
panelThermal = uipanel(figControl, 'Title', 'Thermal Effects', ...
    'Position', [0.05, 0.32, 0.9, 0.08], ...
    'BackgroundColor', panelColor, ...
    'ForegroundColor', accentColor, ...
    'FontWeight', 'bold', ...
    'HighlightColor', accentColor);

uicontrol(panelThermal, 'Style', 'text', ...
    'String', 'Temperature Change:', ...
    'Position', [20, 20, 120, 20], ...
    'HorizontalAlignment', 'left', ...
    'BackgroundColor', panelColor);

editDeltaT = uicontrol(panelThermal, 'Style', 'edit', ...
    'String', '0', ...
    'Position', [150, 20, 80, 25], ...
    'BackgroundColor', 'white', ...
    'Callback', @validateNumericInput);

uicontrol(panelThermal, 'Style', 'text', ...
    'String', 'K', ...
    'Position', [235, 20, 20, 20], ...
    'BackgroundColor', panelColor);

uicontrol(panelThermal, 'Style', 'text', ...
    'String', 'Thermal Expansion:', ...
    'Position', [280, 20, 120, 20], ...
    'HorizontalAlignment', 'left', ...
    'BackgroundColor', panelColor);

editAlpha = uicontrol(panelThermal, 'Style', 'edit', ...
    'String', '12e-6', ...
    'Position', [410, 20, 80, 25], ...
    'BackgroundColor', 'white', ...
    'Callback', @validateNumericInput);

uicontrol(panelThermal, 'Style', 'text', ...
    'String', '1/K', ...
    'Position', [495, 20, 30, 20], ...
    'BackgroundColor', panelColor);

% Add adaptive mesh panel
panelAdaptive = uipanel(figControl, 'Title', 'Adaptive Mesh', ...
    'Position', [0.05, 0.22, 0.9, 0.08], ...
    'BackgroundColor', panelColor, ...
    'ForegroundColor', accentColor, ...
    'FontWeight', 'bold', ...
    'HighlightColor', accentColor);

cbxAdaptive = uicontrol(panelAdaptive, 'Style', 'checkbox', ...
    'String', 'Enable Adaptive Refinement', ...
    'Position', [20, 20, 150, 25], ...
    'BackgroundColor', panelColor, ...
    'Value', 0, ...
    'Callback', @toggleAdaptiveOptions);

uicontrol(panelAdaptive, 'Style', 'text', ...
    'String', 'Error Tolerance:', ...
    'Position', [180, 20, 100, 20], ...
    'HorizontalAlignment', 'left', ...
    'BackgroundColor', panelColor);

editErrorTol = uicontrol(panelAdaptive, 'Style', 'edit', ...
    'String', '0.1', ...
    'Position', [280, 20, 60, 25], ...
    'Enable', 'off', ...
    'BackgroundColor', 'white', ...
    'Callback', @validateNumericInput);

uicontrol(panelAdaptive, 'Style', 'text', ...
    'String', 'Max Refinements:', ...
    'Position', [360, 20, 100, 20], ...
    'HorizontalAlignment', 'left', ...
    'BackgroundColor', panelColor);

editMaxRef = uicontrol(panelAdaptive, 'Style', 'edit', ...
    'String', '3', ...
    'Position', [460, 20, 60, 25], ...
    'Enable', 'off', ...
    'BackgroundColor', 'white', ...
    'Callback', @validateIntegerInput);

% Load and Boundary Panel with visual feedback
panelBC = uipanel(figControl, 'Title', 'Load and Boundary Conditions', ...
    'Position', [0.05, 0.22, 0.9, 0.18], ...
    'BackgroundColor', panelColor, ...
    'ForegroundColor', accentColor, ...
    'FontWeight', 'bold', ...
    'HighlightColor', accentColor);

% Add boundary condition controls
edgeLabels = {'Left Edge:', 'Right Edge:', 'Bottom Edge:', 'Top Edge:'};
edgePositions = [20, 70; 350, 70; 20, 35; 350, 35];
popupEdges = zeros(1, 4);

for i = 1:4
    uicontrol(panelBC, 'Style', 'text', ...
        'String', edgeLabels{i}, ...
        'Position', [edgePositions(i,1), edgePositions(i,2), 100, 20], ...
        'HorizontalAlignment', 'left', ...
        'BackgroundColor', panelColor);
    
    popupEdges(i) = uicontrol(panelBC, 'Style', 'popupmenu', ...
        'String', {'Free (F)', 'Simply Supported (S)', 'Clamped (C)'}, ...
        'Position', [edgePositions(i,1) + 100, edgePositions(i,2), 150, 25], ...
        'Value', 2); % Default to Simply Supported
end

% Add load value input
uicontrol(panelBC, 'Style', 'text', ...
    'String', 'Load Value:', ...
    'Position', [20, 105, 100, 20], ...
    'HorizontalAlignment', 'left', ...
    'BackgroundColor', panelColor);

editLoad = uicontrol(panelBC, 'Style', 'edit', ...
    'String', '1000', ...
    'Position', [120, 105, 100, 25], ...
    'BackgroundColor', 'white', ...
    'Callback', @validateNumericInput);

uicontrol(panelBC, 'Style', 'text', ...
    'String', 'N/m²', ...
    'Position', [225, 105, 40, 20], ...
    'BackgroundColor', panelColor);

% Results Panel with enhanced visualization options
panelResults = uipanel(figControl, 'Title', 'Results Display', ...
    'Position', [0.05, 0.11, 0.9, 0.09], ...
    'BackgroundColor', panelColor, ...
    'ForegroundColor', accentColor, ...
    'FontWeight', 'bold', ...
    'HighlightColor', accentColor);

% Add plot type selection
uicontrol(panelResults, 'Style', 'text', ...
    'String', 'Plot Type:', ...
    'Position', [20, 20, 80, 20], ...
    'HorizontalAlignment', 'left', ...
    'BackgroundColor', panelColor);

popupPlotType = uicontrol(panelResults, 'Style', 'popupmenu', ...
    'String', {'Displacement', 'Stress', 'Strain Energy'}, ...
    'Position', [100, 20, 150, 25], ...
    'Value', 1);

% Add scale factor slider
uicontrol(panelResults, 'Style', 'text', ...
    'String', 'Scale Factor:', ...
    'Position', [260, 20, 80, 20], ...
    'HorizontalAlignment', 'left', ...
    'BackgroundColor', panelColor);

sliderScale = uicontrol(panelResults, 'Style', 'slider', ...
    'Min', 0.1, 'Max', 10, 'Value', 1, ...
    'Position', [340, 20, 100, 20], ...
    'TooltipString', 'Adjust deformation scale factor', ...
    'Callback', @updateScaleFactor);

txtScale = uicontrol(panelResults, 'Style', 'text', ...
    'String', '1.0x', ...
    'Position', [445, 20, 40, 20], ...
    'HorizontalAlignment', 'left', ...
    'BackgroundColor', panelColor);

% Add colormap selection
uicontrol(panelResults, 'Style', 'text', ...
    'String', 'Colormap:', ...
    'Position', [500, 20, 80, 20], ...
    'HorizontalAlignment', 'left', ...
    'BackgroundColor', panelColor);

popupColormap = uicontrol(panelResults, 'Style', 'popupmenu', ...
    'String', {'jet', 'parula', 'turbo', 'hot', 'cool'}, ...
    'Position', [580, 20, 100, 25], ...
    'Value', 1);

% Add animation checkbox for vibration/buckling
cbxAnimate = uicontrol(panelResults, 'Style', 'checkbox', ...
    'String', 'Animate Results', ...
    'Position', [690, 20, 120, 25], ...
    'Value', 0, ...
    'BackgroundColor', panelColor, ...
    'Enable', 'off');

% Add progress panel with more detailed feedback
panelProgress = uipanel(figControl, 'Title', 'Tiến trình phân tích', ...
    'Position', [0.05, 0.02, 0.9, 0.07], ...
    'BackgroundColor', panelColor, ...
    'ForegroundColor', accentColor, ...
    'FontWeight', 'bold', ...
    'HighlightColor', accentColor);

% Tạo progress bar bằng uipanel thay vì axes
progressBar = uipanel(panelProgress, ...
    'Position', [0.05, 0.2, 0.7, 0.6], ...
    'BackgroundColor', [0.9 0.9 0.9]);

progressFill = uipanel(progressBar, ...
    'Position', [0 0 0 1], ...
    'BackgroundColor', buttonColor);

% Status text
txtProgress = uicontrol(panelProgress, 'Style', 'text', ...
    'Position', [20, 10, 260, 20], ...
    'String', 'Sẵn sàng', ...
    'BackgroundColor', panelColor);

% Run button with cancel option
btnRun = uicontrol(panelProgress, 'Style', 'pushbutton', ...
    'String', 'Run Analysis', ...
    'Position', [580, 10, 100, 30], ...
    'BackgroundColor', buttonColor, ...
    'ForegroundColor', 'white', ...
    'Callback', @runAnalysis);

btnCancel = uicontrol(panelProgress, 'Style', 'pushbutton', ...
    'String', 'Cancel', ...
    'Position', [690, 10, 80, 30], ...
    'BackgroundColor', [0.8 0.3 0.3], ...
    'ForegroundColor', 'white', ...
    'Enable', 'off', ...
    'Callback', @cancelAnalysis);

% Add a status bar at the bottom
statusBar = uicontrol(figControl, 'Style', 'text', ...
    'Position', [10, 5, 780, 20], ...
    'BackgroundColor', backgroundColor, ...
    'ForegroundColor', [0.4 0.4 0.4], ...
    'String', 'Ready', ...
    'HorizontalAlignment', 'left');

% Enhanced validation functions
function validateNumericInput(src, ~)
    val = str2double(get(src, 'String'));
    if isnan(val) || ~isreal(val)
        set(statusBar, 'String', 'Error: Please enter a valid number', ...
            'ForegroundColor', [0.8 0 0]);
        set(src, 'String', '0', 'BackgroundColor', [1 0.9 0.9]);
        return;
    end
    set(src, 'BackgroundColor', 'white');
    set(statusBar, 'String', 'Input validated', ...
        'ForegroundColor', [0.4 0.4 0.4]);
end

function validateIntegerInput(src, ~)
    val = str2double(get(src, 'String'));
    if isnan(val) || ~isreal(val) || val <= 0 || mod(val, 1) ~= 0
        set(statusBar, 'String', 'Error: Please enter a positive integer', ...
            'ForegroundColor', [0.8 0 0]);
        set(src, 'String', '1', 'BackgroundColor', [1 0.9 0.9]);
        return;
    end
    set(src, 'BackgroundColor', 'white');
    set(statusBar, 'String', 'Input validated', ...
        'ForegroundColor', [0.4 0.4 0.4]);
end

function validateFractionInput(src, ~)
    str = get(src, 'String');
    if contains(str, '/')
        parts = strsplit(str, '/');
        if length(parts) == 2
            num = str2double(parts{1});
            den = str2double(parts{2});
            if isnan(num) || isnan(den) || den == 0
                set(statusBar, 'String', 'Error: Please enter a valid fraction (e.g., 5/6)', ...
                    'ForegroundColor', [0.8 0 0]);
                set(src, 'String', '5/6', 'BackgroundColor', [1 0.9 0.9]);
                return;
            end
        else
            set(statusBar, 'String', 'Error: Please enter a valid fraction (e.g., 5/6)', ...
                'ForegroundColor', [0.8 0 0]);
            set(src, 'String', '5/6', 'BackgroundColor', [1 0.9 0.9]);
            return;
        end
    else
        val = str2double(str);
        if isnan(val) || ~isreal(val) || val <= 0
            set(statusBar, 'String', 'Error: Please enter a valid positive number or fraction', ...
                'ForegroundColor', [0.8 0 0]);
            set(src, 'String', '5/6', 'BackgroundColor', [1 0.9 0.9]);
            return;
        end
    end
    set(src, 'BackgroundColor', 'white');
    set(statusBar, 'String', 'Input validated', ...
        'ForegroundColor', [0.4 0.4 0.4]);
end

function toggleAdaptiveOptions(src, ~)
    enable = get(src, 'Value');
    onoff = {'off', 'on'};
    set(editErrorTol, 'Enable', onoff{enable + 1});
    set(editMaxRef, 'Enable', onoff{enable + 1});
end

function showHelp(~, ~)
    helpText = {'Mindlin Plate Analysis Help:', ...
        '', ...
        '1. Select analysis type (Static/Buckling/Vibration)', ...
        '2. Enter material properties (E, ν, ρ)', ...
        '3. Define plate geometry (L, W, h)', ...
        '4. Set mesh density (nx, ny)', ...
        '5. Choose boundary conditions for each edge', ...
        '6. Enter load parameters', ...
        '7. Select desired plot type', ...
        '8. Click Run Analysis', ...
        '', ...
        'For more information, see documentation.'};
    helpdlg(helpText, 'Analysis Help');
end

function previewMesh(~, ~)
    try
        nx = str2double(get(editElementsX, 'String'));
        ny = str2double(get(editElementsY, 'String'));
        L = str2double(get(editLength, 'String'));
        W = str2double(get(editWidth, 'String'));
        
        [nodes, elements] = generateMesh(L, W, nx, ny);
        
        % Create preview figure
        previewFig = figure('Name', 'Mesh Preview', ...
            'NumberTitle', 'off', ...
            'Position', [850, 400, 500, 400]);
        
        % Plot mesh
        plotMesh(nodes, elements);
        title('Mesh Preview');
        axis equal tight;
        grid on;
        
        set(statusBar, 'String', 'Mesh preview generated', ...
            'ForegroundColor', [0 0.6 0]);
    catch ME
        set(statusBar, 'String', ['Mesh preview error: ' ME.message], ...
            'ForegroundColor', [0.8 0 0]);
    end
end

function plotMesh(nodes, elements)
    hold on;
    % Plot elements
    for el = 1:size(elements, 1)
        nodeIds = elements(el, 2:5);
        xe = nodes(nodeIds, 2);
        ye = nodes(nodeIds, 3);
        
        % Plot element edges
        plot([xe; xe(1)], [ye; ye(1)], 'b-', 'LineWidth', 0.5);
    end
    
    % Plot nodes
    plot(nodes(:,2), nodes(:,3), 'r.', 'MarkerSize', 8);
    
    xlabel('X (m)');
    ylabel('Y (m)');
    grid on;
    axis equal;
end

function showStaticResults(params, scaleFactor)
    if nargin < 2, scaleFactor = 1; end
    try
        % Create new figure window for static analysis results
        figResults = figure('Name', 'Kết quả phân tích tĩnh', ...
            'NumberTitle', 'off', ...
            'Position', [850, 100, 900, 600]);
        
        % Run analysis
        [nodes, elements] = generateMesh(params.L, params.W, params.nx, params.ny);
        [K, F] = assembleSystem(nodes, elements, params.E, params.poisson, ...
            params.thickness, params.loadValue);
        [K_mod, F_mod] = applyBoundaryConditions(K, F, nodes, params.boundaryConditions);
        U = K_mod\F_mod;
        
        % Get colormap selection properly
        colormaps = get(popupColormap, 'String');
        selectedColormap = colormaps{get(popupColormap, 'Value')};
        
        % Use enhanced plotting with error handling
        plotResults(nodes, elements, U * scaleFactor, 1, params.plotType, selectedColormap, ...
            get(cbxAnimate, 'Value'));
            
    catch ME
        checkGraphicsError(ME);
    end
end

function showBucklingResults(params, scaleFactor)
    if nargin < 2, scaleFactor = 1; end
    try
        % Create new figure window for buckling analysis results
        figResults = figure('Name', 'Buckling Analysis Results', ...
            'NumberTitle', 'off', ...
            'Position', [850, 100, 900, 600]);
        
        % Run buckling analysis
        [nodes, elements] = generateMesh(params.L, params.W, params.nx, params.ny);
        [K, ~] = assembleSystem(nodes, elements, params.E, params.poisson, ...
            params.thickness, 0);
        Kg = assembleGeometricStiffness(nodes, elements, params.loadValue);
        [K_mod, Kg_mod] = applyBucklingBoundaryConditions(K, Kg, nodes, params.boundaryConditions);
        [V, D] = eigs(K_mod, Kg_mod, 5, 'smallestabs');
        
        % Get colormap selection properly
        colormaps = get(popupColormap, 'String');
        selectedColormap = colormaps{get(popupColormap, 'Value')};
        
        % Use enhanced plotting with error handling
        plotResults(nodes, elements, V(:,1) * scaleFactor, 2, params.plotType, selectedColormap, ...
            get(cbxAnimate, 'Value'));
        
        % Display critical load factors in status bar
        criticalLoads = sort(diag(D), 'ascend');
        set(statusBar, 'String', sprintf('Critical load factors: %.4f, %.4f, %.4f', ...
            criticalLoads(1:3)), 'ForegroundColor', [0 0.6 0]);
    catch ME
        checkGraphicsError(ME);
    end
end

function showVibrationResults(params, scaleFactor)
    if nargin < 2, scaleFactor = 1; end
    try
        % Create new figure window for vibration analysis results
        figResults = figure('Name', 'Vibration Analysis Results', ...
            'NumberTitle', 'off', ...
            'Position', [850, 100, 900, 600]);
        
        % Run vibration analysis
        [nodes, elements] = generateMesh(params.L, params.W, params.nx, params.ny);
        [K, ~] = assembleSystem(nodes, elements, params.E, params.poisson, ...
            params.thickness, 0);
        M = assembleMassMatrix(nodes, elements, params.density, params.thickness);
        [K_mod, M_mod] = applyVibrationBoundaryConditions(K, M, nodes, params.boundaryConditions);
        [V, D] = eigs(K_mod, M_mod, 5, 'smallestabs');
        frequencies = sqrt(diag(D))/(2*pi);
        
        % Get colormap selection properly
        colormaps = get(popupColormap, 'String');
        selectedColormap = colormaps{get(popupColormap, 'Value')};
        
        % Use enhanced plotting with error handling
        plotResults(nodes, elements, V(:,1) * scaleFactor, 3, params.plotType, selectedColormap, ...
            get(cbxAnimate, 'Value'));
        
        % Display natural frequencies in status bar
        set(statusBar, 'String', sprintf('Natural frequencies (Hz): %.2f, %.2f, %.2f', ...
            frequencies(1:3)), 'ForegroundColor', [0 0.6 0]);
    catch ME
        checkGraphicsError(ME);
    end
end

function updateAnalysisType(~, ~)
    analysisType = get(popupAnalysis, 'Value');
    
    % Enable/disable animation for dynamic analyses
    if analysisType > 1
        set(cbxAnimate, 'Enable', 'on');
    else
        set(cbxAnimate, 'Enable', 'off', 'Value', 0);
    end
    
    % Update status bar with analysis-specific instructions
    switch analysisType
        case 1
            set(statusBar, 'String', 'Static Analysis: Enter load and boundary conditions');
        case 2
            set(statusBar, 'String', 'Buckling Analysis: Select load type and boundary conditions');
        case 3
            set(statusBar, 'String', 'Vibration Analysis: Enter material density and boundary conditions');
    end
end

function runAnalysis(~, ~)
    % Update status bar
    set(statusBar, 'String', 'Running analysis...', ...
        'ForegroundColor', accentColor);
    drawnow;
    
    try
        % Get analysis parameters
        params = struct();
        
        params.analysisType = get(popupAnalysis, 'Value');
        params.E = str2double(get(editE, 'String'));
        params.poisson = str2double(get(editPoisson, 'String'));
        params.thickness = str2double(get(editThickness, 'String'));
        params.L = str2double(get(editLength, 'String'));
        params.W = str2double(get(editWidth, 'String'));
        params.nx = str2double(get(editElementsX, 'String'));
        params.ny = str2double(get(editElementsY, 'String'));
        params.loadValue = str2double(get(editLoad, 'String'));
        params.plotType = get(popupPlotType, 'Value');
        
        kapaStr = get(editKapa, 'String');
        if contains(kapaStr, '/')
            parts = strsplit(kapaStr, '/');
            params.kapa = str2double(parts{1}) / str2double(parts{2});
        else
            params.kapa = str2double(kapaStr);
        end
        
        bcString = '';
        for i = 1:4
            val = get(popupEdges(i), 'Value');
            switch val
                case 1
                    bcString(i) = 'F';
                case 2
                    bcString(i) = 'S';
                case 3
                    bcString(i) = 'C';
            end
        end
        params.boundaryConditions = bcString;
        
        if params.analysisType == 3
            params.density = str2double(get(editDensity, 'String'));
        elseif params.analysisType == 2
            params.loadType = get(popupLoadType, 'Value');
        end
        
        params.dT = str2double(get(editDeltaT, 'String'));
        params.alpha = str2double(get(editAlpha, 'String'));
        params.useAdaptive = get(cbxAdaptive, 'Value');
        if params.useAdaptive
            params.errorTol = str2double(get(editErrorTol, 'String'));
            params.maxRefinements = str2double(get(editMaxRef, 'String'));
        end
        
        switch params.analysisType
            case 1
                showStaticResults(params);
            case 2
                showBucklingResults(params);
            case 3
                showVibrationResults(params);
        end
        
        set(statusBar, 'String', 'Analysis completed successfully', ...
            'ForegroundColor', [0 0.6 0]);
    catch ME
        set(statusBar, 'String', ['Error: ' ME.message], ...
            'ForegroundColor', [0.8 0 0]);
    end
end

function updateScaleFactor(src, ~)
    % Get the current scale factor from the slider
    scaleFactor = get(src, 'Value');
    set(txtScale, 'String', sprintf('%.1fx', scaleFactor));
    % Get the current figure with results
    figResults = findobj('Type', 'figure', 'Name', 'Static Analysis Results');
    if isempty(figResults)
        figResults = findobj('Type', 'figure', 'Name', 'Buckling Analysis Results');
    end
    if isempty(figResults)
        figResults = findobj('Type', 'figure', 'Name', 'Vibration Analysis Results');
    end
    if ~isempty(figResults)
        figure(figResults);
        params = getCurrentConfig();
        % Pass scaleFactor to plotting functions if possible
        try
            switch params.analysisType
                case 1
                    showStaticResults(params, scaleFactor);
                case 2
                    showBucklingResults(params, scaleFactor);
                case 3
                    showVibrationResults(params, scaleFactor);
            end
        catch ME
            set(statusBar, 'String', ['Plot update error: ' ME.message], ...
                'ForegroundColor', [0.8 0 0]);
        end
    end
end

function saveConfig(~, ~)
    config = getCurrentConfig();
    [filename, pathname] = uiputfile('*.mat', 'Save Configuration As');
    if filename ~= 0
        save(fullfile(pathname, filename), 'config');
        set(statusBar, 'String', 'Configuration saved successfully', ...
            'ForegroundColor', [0 0.6 0]);
    end
end

function loadConfig(~, ~)
    [filename, pathname] = uigetfile('*.mat', 'Load Configuration');
    if filename ~= 0
        data = load(fullfile(pathname, filename));
        if isfield(data, 'config')
            applyConfig(data.config);
            set(statusBar, 'String', 'Configuration loaded successfully', ...
                'ForegroundColor', [0 0.6 0]);
        end
    end
end

function config = getCurrentConfig()
    config = struct();
    config.analysisType = get(popupAnalysis, 'Value');
    config.E = str2double(get(editE, 'String'));
    config.poisson = str2double(get(editPoisson, 'String'));
    config.thickness = str2double(get(editThickness, 'String'));
    config.L = str2double(get(editLength, 'String'));
    config.W = str2double(get(editWidth, 'String'));
    config.nx = str2double(get(editElementsX, 'String'));
    config.ny = str2double(get(editElementsY, 'String'));
    config.loadValue = str2double(get(editLoad, 'String'));
    config.plotType = get(popupPlotType, 'Value');
    config.boundaryConditions = getBoundaryString();
    config.thermalDT = str2double(get(editDeltaT, 'String'));
    config.thermalAlpha = str2double(get(editAlpha, 'String'));
    config.useAdaptive = get(cbxAdaptive, 'Value');
    if config.useAdaptive
        config.errorTol = str2double(get(editErrorTol, 'String'));
        config.maxRefinements = str2double(get(editMaxRef, 'String'));
    end
end

function applyConfig(config)
    set(popupAnalysis, 'Value', config.analysisType);
    set(editE, 'String', num2str(config.E));
    set(editPoisson, 'String', num2str(config.poisson));
    set(editThickness, 'String', num2str(config.thickness));
    set(editLength, 'String', num2str(config.L));
    set(editWidth, 'String', num2str(config.W));
    set(editElementsX, 'String', num2str(config.nx));
    set(editElementsY, 'String', num2str(config.ny));
    set(editLoad, 'String', num2str(config.loadValue));
    set(popupPlotType, 'Value', config.plotType);
    applyBoundaryString(config.boundaryConditions);
    set(editDeltaT, 'String', num2str(config.thermalDT));
    set(editAlpha, 'String', num2str(config.thermalAlpha));
    set(cbxAdaptive, 'Value', config.useAdaptive);
    if config.useAdaptive
        set(editErrorTol, 'String', num2str(config.errorTol));
        set(editMaxRef, 'String', num2str(config.maxRefinements));
    end
    updateAnalysisType();
end

function loadPreviousResults(~, ~)
    [filename, pathname] = uigetfile('*.mat', 'Load Previous Results');
    if filename ~= 0
        previousResults = load(fullfile(pathname, filename));
        if isfield(previousResults, 'results')
            setappdata(figControl, 'PreviousResults', previousResults.results);
            set(findobj(compareMenu, 'Label', 'Compare Analyses'), 'Enable', 'on');
        end
    end
end

function compareAnalyses(~, ~)
    previousResults = getappdata(figControl, 'PreviousResults');
    if ~isempty(previousResults)
        showComparisonDialog(previousResults, getCurrentResults());
    end
end

function updateProgress(stage, progress)
    if nargin < 2
        progress = 0;
    end
    % Update progress bar
    set(progressFill, 'Position', [0 0 progress 1]);
    set(txtProgress, 'String', sprintf('%s: %.0f%%', stage, progress*100));
    drawnow;
end

function checkGraphicsError(ME)
    if contains(ME.message, 'matlab.graphics.axis.Axes')
        warning('Lỗi trục đồ thị: %s', ME.message);
        % Handle error by creating a new figure
        figure;
        return;
    end
    rethrow(ME);
end

function showMeshQuality(nodes, elements)
    nElements = size(elements, 1);
    aspectRatio = zeros(nElements, 1);
    skewness = zeros(nElements, 1);
    
    for el = 1:nElements
        nodeIds = elements(el, 2:5);
        xe = nodes(nodeIds, 2);
        ye = nodes(nodeIds, 3);
        
        dx = max(xe) - min(xe);
        dy = max(ye) - min(ye);
        aspectRatio(el) = max(dx/dy, dy/dx);
        
        angles = calculateElementAngles(xe, ye);
        skewness(el) = max(abs(angles - 90)) / 90;
    end
    
    figure('Name', 'Mesh Quality Assessment', ...
           'NumberTitle', 'off', ...
           'Position', [850, 400, 800, 400]);
    
    subplot(1,2,1);
    histogram(aspectRatio);
    title('Element Aspect Ratio');
    xlabel('Aspect Ratio');
    ylabel('Number of Elements');
    
    subplot(1,2,2);
    histogram(skewness);
    title('Element Skewness');
    xlabel('Skewness');
    ylabel('Number of Elements');
    
    fprintf('Mesh Quality Metrics:\n');
    fprintf('Aspect Ratio - Min: %.2f, Max: %.2f, Mean: %.2f\n', ...
            min(aspectRatio), max(aspectRatio), mean(aspectRatio));
    fprintf('Skewness    - Min: %.2f, Max: %.2f, Mean: %.2f\n', ...
            min(skewness), max(skewness), mean(skewness));
end

function angles = calculateElementAngles(xe, ye)
    angles = zeros(4,1);
    for i = 1:4
        j = mod(i, 4) + 1;
        k = mod(i-2, 4) + 1;
        v1 = [xe(j)-xe(i), ye(j)-ye(i)];
        v2 = [xe(k)-xe(i), ye(k)-ye(i)];
        
        cos_theta = dot(v1,v2)/(norm(v1)*norm(v2));
        angles(i) = acosd(cos_theta);
    end
end

function bcString = getBoundaryString()
    % Returns a 4-character string for boundary conditions based on popupEdges
    bcString = '';
    for i = 1:4
        val = get(popupEdges(i), 'Value');
        switch val
            case 1
                bcString(i) = 'F';
            case 2
                bcString(i) = 'S';
            case 3
                bcString(i) = 'C';
        end
    end
end

end